####
#git
####
#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        git:
#          uri: https://github.com/carnellj/config-repo/
#          searchPaths: licensingservice,organizationservice
#          username: native-cloud-apps
#          password: 0ffended


####
#Classpath and file-based solution
####

server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/,classpath:config/licensingservice,classpath:config/organizationservice
#          searchLocations: file://<chapter 3>/confsvr/src/main/resources/config/licensingservice,
#            file://<chapter 3>confsvr/src/main/resources/config/organizationservice
