spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://192.168.3.4:5432/dev_db"
spring.datasource.username: "postgres"
spring.datasource.password: "{cipher}717c4bf3dffae846e247f81b96ffda354da3c7d24682929056b1cb937b590d4b"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: "false"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
